import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Raleway } from 'next/font/google';
import  Navbar  from "./components/Navbar/Navbar";
import { Suspense } from "react";
import MusicPlayer from "./components/MusicPlayer/TestPlayer";
import { MusicPlayerProvider } from "./context/NewContext";

import NewNavbar from "./components/Navbar/NewNavbar";
const raleway = Raleway({ subsets: ['latin'], weight: ['400', '700'] });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${raleway.className} antialiased`}
      >
        <div className="fixed top-0 left-0 w-full z-50 h-[5vh]">
            <NewNavbar />
        </div>
        <MusicPlayerProvider>
          <div className=" relative  w-full h-[calc(100vh-5vh)]" >
            <Suspense fallback={<div>Loading...</div>}>
                {children}
            </Suspense>
            <MusicPlayer />
          </div>
            
        </MusicPlayerProvider>
       
      </body>
    </html>
  );
}
